#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 2
#SBATCH	-t 00:30:00
#SBATCH -J illumina_trimmomatic
#SBATCH -o %j.out
#SBATCH -e %j.err

module load bioinfo-tools
module load trimmomatic
cd /home/juliasul/GenomeAnalysis/data/4_Tean_Teh_2017/illumina_data

trimmomatic PE SRR6058604_scaffold_06.1P.fastq.gz SRR6058604_scaffold_06.2P.fastq.gz illumina_scaffold06.paired.forward.trimmed.fastq.gz illumina_scaffold06.unpaired.forward.trimmed.fastq.gz illumina_scaffold06.paired.reverse.trimmed.fastq.gz illumina_scaffold06.unpaired.reverse.trimmed.fastq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 MINLEN:36 
trimmomatic PE SRR6058604_scaffold_10.1P.fastq.gz SRR6058604_scaffold_10.2P.fastq.gz  illumina_scaffold10.paired.forward.trimmed.fastq.gz illumina_scaffold10.unpaired.forward.trimmed.fastq.gz illumina_scaffold10.paired.reverse.trimmed.fastq.gz illumina_scaffold10.unpaired.reverse.trimmed.fastq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 MINLEN:36
trimmomatic PE SRR6058604_scaffold_11.1P.fastq.gz SRR6058604_scaffold_11.2P.fastq.gz  illumina_scaffold11.paired.forward.trimmed.fastq.gz illumina_scaffold11.unpaired.forward.trimmed.fastq.gz illumina_scaffold11.paired.reverse.trimmed.fastq.gz illumina_scaffold11.unpaired.reverse.trimmed.fastq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 MINLEN:36
