#!/bin/bash -l
#SBATCH -A uppmax2023-2-3
#SBATCH -p core
#SBATCH -n 4
#SBATCH	-t 24:00:00
#SBATCH -J pacbio_canu


module load bioinfo-tools
module load canu

cd /home/juliasul/GenomeAnalysis/data/4_Tean_Teh_2017/pacbio_data/

canu -p pacbioassembly -d  /home/juliasul/GenomeAnalysis/DNA_prep_assembly_pacbio genomeSize=42.1g -pacbio SRR6037732_scaffold_06.fq.gz SRR6037732_scaffold_10.fq.gz SRR6037732_scaffold_11.fq.gz




