#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 10
#SBATCH	-t 05:00:00
#SBATCH -M snowy
#SBATCH -J RNA_trimmed_fastqc
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load FastQC

cd /proj/genomeanalysis2023/nobackup/work/jusu_RNA/trimmomatic

fastqc -o /home/juliasul/GenomeAnalysis/RNA_prep/fastQC_trimmed -t 10 RNA_sc06* RNA_sc10* RNA_sc11*
