#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 10
#SBATCH	-t 5:00:00
#SBATCH -J quast
#SBATCH -M snowy
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load RepeatMasker

cd /proj/genomeanalysis2023/nobackup/work/jusu_quast


RepeatMasker -pa 10 -species rosids -html -dir repeatmasker/scaffold10 assembly_corrected_scaffold10.fasta
