#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 3
#SBATCH	-t 03:00:00
#SBATCH -J samtools_view
#SBATCH -M snowy


module load bioinfo-tools
module load samtools

cd /proj/genomeanalysis2023/nobackup/work/jusu_bwa

samtools view -S -b aligned_scaffold06.sam > aligned_scaffold06.bam
samtools view -S -b aligned_scaffold10.sam > aligned_scaffold10.bam
samtools view -S -b aligned_scaffold11.sam > aligned_scaffold11.bam
