#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 3
#SBATCH	-t 03:00:00
#SBATCH -J samtools_view
#SBATCH -M snowy


module load bioinfo-tools
module load samtools

cd /home/juliasul/GenomeAnalysis/DNA_post_assembly_mod/

samtools sort -o aligned_scaffold06_sorted.bam aligned_scaffold06.bam
samtools sort -o aligned_scaffold10_sorted.bam aligned_scaffold10.bam
samtools sort -o aligned_scaffold11_sorted.bam aligned_scaffold11.bam
