#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 10
#SBATCH	-t 03:00:00
#SBATCH -J samtools_index_bam
#SBATCH -M snowy
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load samtools

cd /proj/genomeanalysis2023/nobackup/work/jusu/jusu_STAR/align/bamfiles/bamfiles_sorted

samtools index SRR_66_sc06.bam
samtools index SRR_66_sc10.bam
samtools index SRR_66_sc11.bam

samtools index SRR_67_sc06.bam
samtools index SRR_67_sc10.bam
samtools index SRR_67_sc11.bam

samtools index SRR_69_sc06.bam
samtools index SRR_69_sc10.bam
samtools index SRR_69_sc11.bam

samtools index SRR_92_sc06.bam
samtools index SRR_92_sc10.bam
samtools index SRR_92_sc11.bam

samtools index SRR_93_sc06.bam
samtools index SRR_93_sc10.bam
samtools index SRR_93_sc11.bam

samtools index SRR_94_sc06.bam
samtools index SRR_94_sc10.bam
samtools index SRR_94_sc11.bam

samtools index SRR_95_sc06.bam
samtools index SRR_95_sc10.bam
samtools index SRR_95_sc11.bam

samtools index SRR_96_sc06.bam
samtools index SRR_96_sc10.bam
samtools index SRR_96_sc11.bam

samtools index SRR_97_sc06.bam
samtools index SRR_97_sc10.bam
samtools index SRR_97_sc11.bam
