#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 3
#SBATCH	-t 05:00:00
#SBATCH -M snowy
#SBATCH -J htseq_sc06_stolen_genemark
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load htseq

cd /proj/genomeanalysis2023/nobackup/work/jusu/jusu_htseq/sc06

bam=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_STAR/align/bamfiles/bamfiles_sorted
gtf_sc06=/proj/genomeanalysis2023/nobackup/work/andreasb/codebackup/braker/durioZibethinus/GeneMark-ET

htseq-count -f bam -r pos \
$bam/SRR_66_sc06.bam $bam/SRR_67_sc06.bam $bam/SRR_69_sc06.bam $bam/SRR_92_sc06.bam $bam/SRR_93_sc06.bam $bam/SRR_94_sc06.bam $bam/SRR_95_sc06.bam $bam/SRR_96_sc06.bam $bam/SRR_97_sc06.bam \
$gtf_sc06/genemark.gtf
 

