#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 10
#SBATCH	-t 10:00:00
#SBATCH -M snowy
#SBATCH -J braker_sc11
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.33-es_Perl5.24.1

AUGUSTUS_CONFIG_PATH=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_braker/augustus_config

AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin

AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts

GENEMARK_PATH=/sw/bioinfo/GeneMark/4.33-es/snowy

cd /proj/genomeanalysis2023/nobackup/work/jusu/jusu_braker/sc11
bamdir=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_STAR/align/bamfiles

braker.pl --useexisting species=D_zibethinus --genome=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_quast/repeatmasker/scaffold11/assembly_corrected_scaffold11.fasta.masked --softmasking\
       --bam=$bamdir/SRR_66_sc11.bam,$bamdir/SRR_67_sc11.bam,$bamdir/SRR_69_sc11.bam,$bamdir/SRR_92_sc11.bam,$bamdir/SRR_93_sc11.bam,$bamdir/SRR_94_sc11.bam,$bamdir/SRR_95_sc11.bam,$bamdir/SRR_96_sc11.bam,$bamdir/SRR_97_sc11.bam \
	--cores=10 --UTR=on  
