#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -p core
#SBATCH -n 10
#SBATCH	-t 05:00:00
#SBATCH -M snowy
#SBATCH -J braker_sc06_restart
#SBATCH --mail-type=ALL
#SBATCH --mail-user=julia.sulyaeva.2968@student.uu.se

module load bioinfo-tools
module load braker/2.1.1_Perl5.24.1
module load augustus/3.2.3_Perl5.24.1
module load bamtools/2.5.1
module load blast/2.9.0+
module load GenomeThreader/1.7.0
module load samtools/1.8
module load GeneMark/4.33-es_Perl5.24.1

AUGUSTUS_CONFIG_PATH=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_braker/augustus_config
chmod a+w -R /proj/genomeanalysis2023/nobackup/work/jusu/jusu_braker/augustus_config/species/

AUGUSTUS_BIN_PATH=/sw/bioinfo/augustus/3.4.0/snowy/bin

AUGUSTUS_SCRIPTS_PATH=/sw/bioinfo/augustus/3.4.0/snowy/scripts

GENEMARK_PATH=/sw/bioinfo/GeneMark/4.33-es/snowy

cp -vf /sw/bioinfo/GeneMark/4.33-es/snowy/gm_key $HOME/.gm_key

cd /proj/genomeanalysis2023/nobackup/work/jusu/jusu_braker/sc06
bamdir=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_STAR/align/bamfiles

braker.pl --species=D_zibethinus --useexisting --genome=/proj/genomeanalysis2023/nobackup/work/jusu/jusu_quast/repeatmasker/scaffold06/assembly_corrected_scaffold06.fasta.masked --softmasking\
       --bam=$bamdir/SRR_66_sc06.bam,$bamdir/SRR_67_sc06.bam,$bamdir/SRR_69_sc06.bam,$bamdir/SRR_92_sc06.bam,$bamdir/SRR_93_sc06.bam,$bamdir/SRR_94_sc06.bam,$bamdir/SRR_95_sc06.bam,$bamdir/SRR_96_sc06.bam,$bamdir/SRR_97_sc06.bam \
	--cores=10 --UTR=on --hints=/home/juliasul/GenomeAnalysis/DNA_annotation/sc06/braker/D_zibethinus/hintsfile.gff --skipAllTraining --skipOptimize  
